import Head from "next/head";
import Image from "next/image";
import useBlockchain from "../hooks/use-blockchain";
import { NavBar } from "../components/NavBar";
import Banner from "../components/Banner";
import { NFT } from "../components/NFT";
import { Footer } from "../components/Footer";
import fetchNfts from "../utils/fetchNfts";

export async function getServerSideProps() {
  const data = await fetchNfts();
  return {
    props: {
      nfts: data.data.items,
    },
  };
}

export default function Home({ nfts }) {
  const { authProvider, network, address, contract } = useBlockchain();

  return (
    <div className="">
      <Head>
        <title>NFT ZONE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-8">
          <h2 className="text-4xl font-semibold pb-5">Recently Listed NFTs</h2>

          <div className="grid grid-cols-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 pt-4">
            {nfts?.map((nft) => {
              return (
                <NFT
                  key={nft.id}
                  id={nft.id}
                  name={nft.name}
                  description={nft.description}
                  image={nft.image}
                  price={nft.price}
                  seller={nft.seller}
                  show={true}
                />
              );
            })}
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
